### ISSUE TITLE
Sample runs from 14.5 on Node to 8.1 seconds on 4 warp threads. Could be faster?

### ISSUE THREAD

**Issue by domscale** [ScaleDynamics/starnode-doc#2]
```
256 prime factorizations computed in 14.508 seconds by Node with its unique thread on a 4 CPU(s) host
256 prime factorizations computed in 8.098 seconds by Starnode with 4 warp thread(s) on a 4 CPU(s) host
```
=> Speed up factor: 1.9. Aside my terminal, I just have my Chrome browser open with the minimum tabs to run this trial

Also, the big output of the prime fact "pollutes" a bit my terminal so It I can't remember the exact time it was with node, it's a bit painful to scroll and fin the node time. Couldn't we output those in a file (that can then be "diffed" to make sure we get the same results and then we display only the chrono in the console.

**Comment by jpl-scale** [comment]
Yes, speed up is fonction of your computer, processor, memory, memory hierarchy, file system, load of your computer, ...

The code must be simple, so, no file here. We have two choices here, remove the output, or leave it. The output demonstrate that the computation is done. I think it is not a very big deal to go through your terminal history. Anyway, we can use the stderr/stdout to help the user with that.

**Comment by lc3t35** [comment]
256 prime factorizations...on my old iMac 2,8Ghz i5 - 16Go DDR3 :
16.808 seconds by Node with its unique thread on a 4 CPU(s) host
5.736 seconds by Starnode with 4 warp thread(s) on a 4 CPU(s) host
