### ISSUE TITLE
2 Warnings during npm install starnode

### ISSUE THREAD

**Issue by lc3t35** [ScaleDynamics/starnode-doc#4]
OS: macOS High Sierra 10.13.6
Node: 8.9.4 - /usr/local/bin/node
Yarn: 1.13.0 - ~/.yarn/bin/yarn
npm: 5.6.0 - /usr/local/bin/npm

````
npm install -g https://starbase.scaledynamics.io/download/public/starnode-latest.tgz
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-pIovzzcZAXhIvXUo41sy01V0Qyo= integrity checksum failed when using sha1: wanted sha1-pIovzzcZAXhIvXUo41sy01V0Qyo= but got sha512-CdzaS0G2sfOd/bjdOE6YawRlFq/CTfGBfC0/09g6LIqDYFFbHZr5dkDDt3ozhsr6szXc7ajCxBmAo7X2vqYJug==. (295056 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
````

**Comment by jpl-scale** [comment]
Thanks for your report.

The sha512 is the integrity of `starnode@1.0.0-beta2`.
Not sure about the sha1.

I lean towards an issue with `npm`. Can reproduce the issue with npm@5.6.0, npm@5.7.0 seems broken, and npm@5.7.1 is fine to install starnode.

@lc3t35 could you try with another npm version >= 5.7.1 to know if you have the same behavior than me? 

Thanks.

**Comment by lc3t35** [comment]
no error with npm@5.7.1
```
npm --version
5.7.1
iMac:~ laurent$ npm remove -g starnode@1.0.0-beta2
up to date in 0.06s
iMac:~ laurent$ npm install -g https://starbase.scaledynamics.io/download/public/starnode-latest.tgz
/Users/laurent/.npm-global/bin/starnode -> /Users/laurent/.npm-global/lib/node_modules/starnode/bin/starnodeLauncher.js
+ starnode@1.0.0-beta2
```

**Comment by jpl-scale** [comment]
Thank you so much for your help. I will dig a little more to see if there is something wrong in starnode packaging.
